version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:15-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../import:/import

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  neo4j:
    # Docker image to be used
    image: neo4j:5.15.0-community
    # user: "${UID}:${GID}"

    # The ports that will be accessible from outside the container - HTTP (7474) and Bolt (7687).
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"
    #   - "7474:7474"
    #   - "7687:7687"

    # Uncomment the volumes to be mounted to make them accessible from outside the container.
    network_mode: service:db
    volumes:
      - ../import:/import
      - ../data:/data
      - ../logs:/logs
      - ../conf:/conf
      - ../plugins:/plugins

    # Passes the following environment variables to the container
    environment:
    #  -  NEO4J_AUTH: "neo4j/password"
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_bolt_advertised__address=localhost:7687
      - NEO4J_server_http_advertised__address=localhost:7474
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_memory_pagecache_size=3G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_heap_initial__size=4G
      # - NEO4J_dbms_tx__log_rotation_retention__policy=2G
      # - NEO4J_PLUGINS=["apoc"]


volumes:
  postgres-data:
