from prompts.vdb_prompt import VDBPrompt

if __name__ == '__main__':
    paragraph = """
        Artificial Intelligence (AI) has become one of the most transformative technologies of the 21st century, reshaping industries, economies, and daily life. The importance of AI lies in its ability to process vast amounts of data, recognize patterns, and make decisions with minimal human intervention, which opens up possibilities that were once confined to science fiction. In an increasingly data-driven world, AI has the potential to revolutionize fields as diverse as healthcare, education, finance, transportation, and communication. It is enabling more efficient, personalized, and accurate services, which in turn drive innovation and growth.
        One of AI's most significant contributions is in healthcare, where it is improving diagnostics, treatment planning, and drug discovery. AI-powered algorithms can analyze medical images with a level of detail that surpasses human capability, detecting diseases like cancer at earlier stages. In addition, AI aids in drug discovery by simulating molecular interactions and identifying potential treatments more rapidly than traditional methods, reducing the time and cost associated with bringing new medicines to market. Personalized medicine, where treatments are tailored to individual genetic profiles, is also being made possible by AI’s ability to analyze complex biological data.
        AI’s role in automating processes is equally transformative. In industries such as manufacturing, logistics, and agriculture, AI-driven robots and systems are optimizing production lines, supply chains, and resource management. These efficiencies lead to cost reductions, lower environmental impact, and the ability to meet growing consumer demands without straining human labor. Autonomous vehicles, guided by AI, promise to revolutionize transportation by reducing accidents caused by human error and improving traffic management, potentially making commuting faster and safer for everyone.
        In finance, AI is reshaping how markets operate. Algorithms can analyze financial data in real-time, making predictions and executing trades faster than any human could. This speeds up financial decision-making and increases the accuracy of risk assessments, enabling better investment strategies and fraud detection. AI-powered chatbots and customer service systems are enhancing the banking experience, offering personalized support while reducing operational costs for financial institutions.
        Education is also undergoing a transformation with the integration of AI. AI-driven tools can provide personalized learning experiences, adapting to the individual needs and learning pace of students. By analyzing how students interact with course materials, AI can offer insights into areas of improvement, helping educators tailor their teaching strategies. This personalized approach has the potential to improve student engagement and learning outcomes, making education more accessible and effective on a global scale.
        AI also plays a critical role in addressing some of the world’s most pressing challenges, such as climate change. AI-powered systems can analyze environmental data, predict weather patterns, and optimize energy use, helping societies transition to more sustainable practices. In agriculture, AI is helping farmers optimize crop yields by analyzing soil conditions, predicting weather changes, and identifying pest outbreaks early, ensuring food security for growing populations.
        However, as AI continues to evolve, its ethical implications must be carefully considered. Issues related to privacy, bias, and job displacement require ongoing attention to ensure that the benefits of AI are distributed fairly across society. Nonetheless, AI holds immense promise for creating a future where technology augments human capabilities, leading to greater efficiencies, innovation, and opportunities across every sector. Its importance will only continue to grow as it becomes more deeply integrated into our daily lives.
    """

    # qdrant = QdrantService()
    # doc = Document(paragraph, chunk_size=1)
    # embeddings = doc.load_embeddings()
    # qdrant.insert_vectors("document", embeddings)

    prompt = VDBPrompt(paragraph)
    print(prompt.get_summary())
